#!/bin/bash

# Example Usages:
# ./arc-builder.sh build firmware/examples/blinky.c -> Returns a built hex file in the build directory
# ./arc-builder.sh clean -> Removes all files generated by SDCC. 


build() {
    local entry=$1
    local outdir="build"
    local entryname=$(basename "${entry}" .c)
    
    mkdir -p $outdir

    echo "Building dependencies..."
    for src in firmware/libs/**/*.c; do
        local rel="${outdir}/$(basename ${src%.c}).rel"
        echo "  Compiling $src -> $rel"
        sdcc -mmcs51 --std-sdcc99 -c $src -o $rel
        if [ $? -ne 0 ]; then
            echo "Error compiling $src"
            exit 1
        fi
    done

    echo "Building $entry..."
    local rels=$(ls $outdir/*.rel 2>/dev/null | tr '\n' ' ')
    sdcc -mmcs51 --std-sdcc99 --out-fmt-ihx -o $outdir/$entryname.ihx $entry $rels
    if [ $? -ne 0 ]; then
        echo "Error building $entry"
        exit 1
    fi

    echo "Packing HEX..."
    packihx $outdir/$entryname.ihx > $outdir/$entryname.hex
    
    echo "Done. Output: $outdir/$entryname.hex"
}

clean() {
    rm -f build/*.ihx build/*.lk build/*.lst build/*.mem build/*.rel build/*.rst build/*.sym build/*.asm build/*.map build/*.hex
    echo "Removed all SDCC files successfully!"
    exit 0
}

if [[ -z "$1" ]]; then
    echo "Usage: [build/clean] <files>"
    exit 0
fi

if [[ "$1" == "build" ]]; then
    build $2
fi

if [[ "$1" == "clean" ]]; then
    clean
fi